### ISSUE TITLE
Problem of devicePixelRatio is not 1.0

### ISSUE THREAD

**Issue by HU-xiaobai** [web-arena-x/webarena#19]
Hello, when I run the run.py, I meet the problem of devicePixelRatio is not 1.0 and thus the scores has no value. could you help me how to fixed the problem? I do not find any way to fix the devicePixelRatio. My system is windows 11

<img width="879" alt="1692806086125" src="https://github.com/web-arena-x/webarena/assets/85933274/93745dd1-97ff-4f27-8708-452e1662ead9">

**Comment by HU-xiaobai** [comment]
By the way, it seems the following line with red arrow has problems, which is "env.reset". could you help me to fix the problem?

<img width="627" alt="1692806365525" src="https://github.com/web-arena-x/webarena/assets/85933274/70864409-5758-4d56-ba56-d051eb7bd89b">

**Comment by shuyanzhou** [comment]
Seems like it is a Windows specific issue. 

In the code, we have forced the `device_scale_factor` to be set to `1` [here](https://github.com/web-arena-x/webarena/blob/main/browser_env/envs.py#L146). However, [such a setting may not work on Windows.](https://support.google.com/chrome/thread/161478111/scaling-since-last-update?hl=en)

Can you try to set the scale to 100% to see if the problem persists?
![issue](https://github.com/web-arena-x/webarena/assets/29911200/4a78d28a-e85d-4d2b-ac16-0449212af1fa)

**Comment by animatrionix** [comment]
Hi, I got the same error on Windows and fixed it by commenting out 2 lines of code:

**browser_env\envs.py (line 146):**
```
geolocation=geolocation,
# device_scale_factor=1.0,
```

**browser_env\processors.py (line 93):**
```
device_pixel_ratio = page.evaluate("window.devicePixelRatio").
# assert device_pixel_ratio == 1.0, "devicePixelRatio is not 1.0".
```

Still, a small visual transition error occurs on the website.

It's really very interesting project, **thanks to the developers**.
