### ISSUE TITLE
How to run the webarenam without the administrator privileges？

### ISSUE THREAD

**Issue by leoozy** [web-arena-x/webarena#67]
Hello, and thank you for providing such an excellent environment. Could you please guide me on how to install the environment without needing administrator privileges? Certain operations, like using Playwright, require such privileges. However, many individuals operate Large Language Models on GPU servers where administrator access is not available. This requirement for administrator privileges significantly hinders our ability to utilize the environment effectively. Thank you for your time.

**Comment by shuyanzhou** [comment]
Hi @leoozy,

Can you give more details on this? To my knowledge, dependencies like `playwright` do not require admin privileges. I have tested the [minimal_example](https://github.com/web-arena-x/webarena/blob/main/minimal_example.py) without admin before.

**Comment by frankxu2004** [comment]
If you are experiencing issues running docker images (website environments) on your server without admin privileges, try adding your user to the docker group in Linux. Another option is to run docker images on another server (because website hosting servers do not require GPUs), and access those websites from your GPU server by specifying the URLs.
